#language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t alexsnyx/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexsnyx/docker-react npm run test

deploy:
  #edge: true #activate this for missing bucket_name error
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  #s3 storage
  bucket_name: "elasticbeanstalk-eu-central-1-725254744174"
  # folder in S3 bucket
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY