#language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t alexsnyx/docker-react -f ./6.workflow/frontend/Dockerfile.dev .

script:
  - docker run -e CI=true alexsnyx/docker-react npm run test